organization: "YOUR_ORGANIZATION"
project: "YOUR_PROJECT"
api_key: "YOUR_API_KEY"
prompt: |
  次の英文を日本語に翻訳してください.
  返答では翻訳後だけを答え, それ以外の発言は含めないでください.
  崩れたTeXの表現が含まれていれば修正して記述してください.
  無駄のあるTeXの書き方であれば洗礼された書き方に治してください.
  「\(..\)」や「\[..\]」ではなく「$..$」や「$$..$$」を使ってください.